server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://47.101.144.198:3306/life?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 76530010zz
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
