server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/life?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 10hg2sa231aKSW
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
