spring:
  profiles:
    active: dev
  mvc:
    async:
      request-timeout: 20000

logging:
  config: classpath:log4j2-spring.xml

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
